#!/usr/bin/env bash
# Display username, UID, and home directory path from /etc/passwd

while IFS=":" read -r username _ uid _ _ _ home _
do
  echo "Username: $username"
  echo "UID: $uid"
  echo "Home Directory: $home"
  echo
done < /etc/passwd
