#!/usr/bin/env bash
#This is a comment
y=1
while [ $y -le 12 ]
do
  i=1
  while [ $i -le 60 ]
  do
    echo $i
    if [ $i -eq 60 ]
    then
       echo "Hour: 1"
    fi
   i=$((i+1))
  done
 y=$((y+1))
done
