#!/usr/bin/env bash
#This is a comment
echo $$ > /var/run/myscript.pid 
trap 'echo "I hate the kill command "' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
while true
do
  echo "To infinity and beyond"
done
rm /var/run/myscript.pid
trap 'pkill -15 -f /var/run/myscript.pid' SIGQUIT  SIGTERM 
