#!/usr/bin/env bash
# This is a comment
echo $$ | sudo tee /var/run/myscript.pid > /dev/null
trap 'echo "I hate the kill command"; rm -f /var/run/myscript.pid; exit' SIGTERM
trap 'echo "Y U no love me?!"; rm -f /var/run/myscript.pid; exit' SIGINT
trap 'rm -f /var/run/myscript.pid' EXIT
while true
do
    echo "To infinity and beyond"
    sleep 2
done
