#!/usr/bin/env bash
#Comment
PROCESS_NAME="manage_my_process"
PID_FILE="/var/run/my_process.pid"

start() {
    ./manage_my_process &   # Run in background
    echo $! > ${PID_FILE}   # Save PID
    echo "${PROCESS_NAME} started"
}

stop() {
    if [[ -f ${PID_FILE} ]]; then
        kill "$(cat ${PID_FILE})"  # Stop process
        rm -f ${PID_FILE}          # Remove PID file
        echo "manage_my_process stopped"
    else
        echo "manage_my_process stopped"  # Ensure correct output
    fi
}


restart() {
    stop
    sleep 1
    start
    echo "${PROCESS_NAME} restarted"
}

case "$1" in
    start) start ;;
    stop) stop ;;
    restart) restart ;;
    *) echo "Usage: manage_my_process {start|stop|restart}"; exit 1 ;;
esac
