#!/usr/bin/env bash
#Comment
start () {
  ./manage_my_process &
  echo $! > /var/run/my_process.pid

}
stop () {
  kill -9 /var/run/my_process.pid
  rm -f /var/run/my_process.pid
}

restart () {
  stop
  sleep 1
  start
}

case "$1" in
  start) start ;;
  stop) stop ;;
  restart) restart ;;
  *) echo "Usage: manage_my_process {start|stop|restart}"; exit 1 ;;
esac
